version: '3.8'
services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
    # Uncomment this if you want to change the location of
    # the SQLite DB file within the container
    # DB_SQLITE_FILE: "/data/database.sqlite"

    # Uncomment this if IPv6 is not enabled on your host
    # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  game_test_server:
    image: game-server
    build: .
    ports:
      - '8001:8001'
    volumes:
      - ./back/src/scripts:/app/back/src/scripts
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  game_obby_parkour:
    image: game-server
    environment:
      - GAME_SCRIPT=parkourScript.js
    ports:
      - '8002:8001'
    volumes:
      - ./back/src/scripts:/app/back/src/scripts
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      - game_test_server

  game_football:
    image: game-server
    environment:
      - GAME_SCRIPT=footballScript.js
    ports:
      - '8003:8001'
    volumes:
      - ./back/src/scripts:/app/back/src/scripts
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      - game_test_server
